Repository ORT-FIS-202108/proyecto-grupo1-steinfeld-rameau, pull requests merged in 2021-11, with the labels that each got.

#11 seccion categorias
  src/dominio/categoria.mjs
  src/dominio/lista-categorias.mjs
  src/dominio/lista-peliculas.mjs
  src/dominio/pelicula.mjs
  src/dominio/pelicula.test.js
  src/interfaz/index.html
  src/interfaz/package-lock.json
  src/interfaz/scripts/categorias.js
  src/interfaz/scripts/index.js
  src/interfaz/styles/categoria.scss
  src/interfaz/styles/index.scss
Labels: Interfaz HTML/CSS, FuncionalidadesJS

#13 listar movimientos y nuevos movimientos
  src/dominio/lista-movimientos.mjs
  src/dominio/movimiento.mjs
  src/dominio/pelicula.test.js
  src/interfaz/index.html
  src/interfaz/scripts/categorias.js
  src/interfaz/scripts/index.js
  src/interfaz/scripts/movimientos.js
  src/interfaz/styles/categoria.scss
  src/interfaz/styles/index.scss
  src/interfaz/styles/movimientos.scss
Labels: Interfaz HTML/CSS, FuncionalidadesJS

#17 Validacion Formularios, categorias y movimientos
  src/dominio/lista-categorias.mjs
  src/dominio/lista-movimientos.mjs
  src/interfaz/index.html
  src/interfaz/scripts/categorias.js
  src/interfaz/styles/categoria.scss
Labels: FuncionalidadesJS

#16 Desarrollo/movimientos descarga
  src/interfaz/index.html
  src/interfaz/scripts/exportarDatos.js
  src/interfaz/scripts/index.js
  src/interfaz/scripts/movimientos.js
  src/interfaz/styles/index.scss
  src/interfaz/styles/movimientos.scss
Labels: FuncionalidadesJS

#20 categoria y cambio de select
  src/interfaz/index.html
  src/interfaz/scripts/categorias.js
  src/interfaz/scripts/index.js
  src/interfaz/scripts/movimientos.js
  src/interfaz/styles/movimientos.scss
Labels: bug

#29 test movimientos
  src/dominio/movimientos/lista-movimientos.mjs
  src/dominio/movimientos/movimientos.test.js
  src/interfaz/scripts/categorias.js
Labels: test

#31 ambiente produccion y desarrollo
  install.md
  src/interfaz/package-lock.json
  src/interfaz/package.json
Labels: FuncionalidadesJS

#35 Se arregla un bug y se agrega test para el caso
  README.md
  src/dominio/graficos/graficos.mjs
  src/dominio/graficos/graficos.test.js
Labels: bug

#32 bug con movimientos boton editar
  src/interfaz/scripts/index.js
  src/interfaz/scripts/movimientos.js
Labels: bug

#36 Informe
  docs/accesibilidad/Know_problems.pdf
  docs/accesibilidad/Potential_Problems.pdf
  docs/accesibilidad/configuracion.png
  docs/testing/Sesion_Alvaro_Rameau.pdf
  docs/testing/Sesion_Categorias_Stella_Steinfeld.pdf
  docs/testing/Sesion_Movimientos_Stella_Steinfeld.pdf
  docs/testing/unitario.png
  src/README.md
Labels: documentation
